仮想環境の立ち上げ
shinonome-inc/backend-final-assignment-renyagi pull request #1
Opened 2024-04-04 12:05 UTC by renyagi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-04-11 14:07 UTC, morita-y9 reviewed
1点だけコメントしたので，確認お願いします

2024-04-11 14:07 UTC, morita-y9 commented on accounts/views.py
> +        print(form.cleaned_data)
使っていないなら，この1文は不要です！

2024-04-15 06:04 UTC, IzmYuta requested changes
全体的によく書けていると思います！
数点だけ修正してほしいところがあるのでお願いします！

2024-04-15 06:04 UTC, IzmYuta commented on accounts/forms.py
> +        fields = ("username", "email")
fieldsにはタプル`()`を使うこともできますが、リスト`[]`を使うのが一般的です。

2024-04-15 06:04 UTC, IzmYuta commented on final-assignment/Scripts/Activate.ps1
仮想環境のファイルが含まれています。
gitignoreを編集して`final-assignment`配下のファイルを読み込ませないようにするか、新しく仮想環境を作り直してください。
ちなみに仮想環境は`venv`という名前で作るのが一般的です。
```bash
python -m venv venv
```

2024-04-16 05:21 UTC, renyagi commented
質問です！
本来なら仮想環境を作成したうえで、このリポジトリを組み込むのが正解なのでしょうか？？

2024-04-16 12:19 UTC, IzmYuta commented
> 質問です！ 本来なら仮想環境を作成したうえで、このリポジトリを組み込むのが正解なのでしょうか？？

OSによって構造が変わるので、組み込まないのが正解です。
なので`final-assignment`配下にあるファイル群(Scriptsなど)はgit管理下から除外して大丈夫です。
ちなみに、Macで作成すると画像のようになります(違う構造になっているはずです)。

<img width="235" alt="スクリーンショット 2024-04-16 21 08 46" src="https://github.com/shinonome-inc/backend-final-assignment-renyagi/assets/104307371/57068193-7175-4579-abce-c0dba2c5b26b">

2024-04-19 08:18 UTC, renyagi commented
venuを作成しました。

![image](https://github.com/shinonome-inc/backend-final-assignment-renyagi/assets/105191030/dee9f495-4f00-4735-8495-9ccddb737ee4)

2024-04-19 08:21 UTC, IzmYuta approved these changes
LGTM

2024-04-19 08:22 UTC, merged