Feature/login
shinonome-inc/backend-final-assignment-renyagi pull request #4
Opened 2024-04-28 04:06 UTC by renyagi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-05-03 05:13 UTC, Ash1ey18 commented
お疲れ様です！あさひです！😊
レビューするの遅れて本当に申し訳なかったです🙏

テスト以外はザーッと見て改善できそうなところコメントしてみました！✨
なにかあれば連絡してください！👍

2024-05-03 06:14 UTC, Ash1ey18 commented
テストも見ました！🔥
めちゃくちゃコメント多くなっちゃったけど、ベースは結構いい感じだと思う！！🙆
あと一息！！🍚

2024-05-05 21:25 UTC, Ash1ey18 requested changes

2024-05-05 21:25 UTC, Ash1ey18 commented on templates/accounts/{username}.html
> +	{% csrf_token %}
`csrf_token`は`form`タグと共に使われるものなのでここでは不要です！👍
↓参考URL（分かりづらかったらCSRFと検索して見て下さい😁)
https://docs.djangoproject.com/en/5.0/ref/csrf/

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +    template_name = "accounts/{username}.html"
`{username}.html`ですが、`profile.html`に改名しちゃった方が分かりやすいかもしれないです！👍
このhtmlのファイル名はパス（URLの部分)に影響しないので、開発者が分かりやすいファイル名をつけるのが無難です！✨

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +    form_class = AuthenticationForm
LoginVIewにすでにこと記述はなされているので、削除しちゃってOKです！🔥
↓参考URL
https://ccbv.co.uk/projects/Django/5.0/django.contrib.auth.views/LoginView/
↓このサイトちょーー有用なので汎用Classの中身を知りたくなったときは参照してみてください😆
https://ccbv.co.uk/

2024-05-05 21:25 UTC, Ash1ey18 commented on templates/base.html
> +        <li><a href="{% url 'accounts:login' %}">Login</a></li>
Logoutボタンも追加しちゃってください！👍

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +        return reverse_lazy(settings.LOGIN_REDIRECT_URL, kwargs={"username": username})
どーやら、デフォルトで`LOGIN_REDIRECT_URL`がログイン後の遷移先になっているっぽいです！😳
（自分も今日調べて初めて知りましたw)
なのでここの部分も削除しちゃって大丈夫だと思います！！😊
![image](https://github.com/shinonome-inc/backend-final-assignment-renyagi/assets/110142795/fdf03c58-0207-4a47-8965-13ac49817087)

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +    template_name = "accounts/{username}.html"
あと、UserProfileViewはログイン後限定画面なので、`LoginRequiredMixin`も継承させちゃってください！👍

`LoginRequiredMixin`っていうのは簡単に言うと「ログインしてない人をブロックするバリア」です！
 classの引数に指定するだけで、ログインしていないユーザを自動的にログインURLに遷移させることができます！！✨

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +    template_name = "accounts/{username}.html"
あと、`UserProfileView`はただTemplate(html)をレンダリングするだけのビューなので、
`TemplateView`を継承させちゃいましょう！❤️‍🔥
model変数も削除でいいと思います！

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/views.py
> +        return self.get_queryset().get(username=self.kwargs["username"])
自分も勉強不足でロジックは分からないのですが、get_objectをいじらなくてもtemplate(html)でuserコンテキストを受け取れたはずです！😲　試しに消してみてください！
なんで行けるのかわかったら追って連絡します🫡

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +            reverse_lazy("accounts:user_profile", kwargs={"username": valid_data["username"]}),
「設定したLOGIN_REDIRECT_URLにリダイレクトしている」というテスト要件なので、
` reverse(settings.LOGIN_REDIRECT_URL)`と記述してみてください！！🔥
なお、reverseとreverse_lazyの違いは↓を参照してみてください👍
https://daeudaeu.com/django-reverse_lazy/

2024-05-05 21:25 UTC, Ash1ey18 commented on mysite/settings.py
> +LOGIN_REDIRECT_URL = "accounts:user_profile"
`LOGIN_REDIRECT_URL`は`tweets:home`でお願いします！🙏
![image](https://github.com/shinonome-inc/backend-final-assignment-renyagi/assets/110142795/a17dbc22-486e-49be-89c8-69e833f03abb)

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.url = reverse("accounts:login")
ここも`LOGIN_URL`に変更しましょう！

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +            reverse_lazy("accounts:user_profile", kwargs={"username": valid_data["username"]}),
ここも同様です！

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.assertTrue(User.objects.filter(username=valid_data["username"]).exists())
このコードについて、
見た感じ不要かなって思うのですが、何かしらの意図があるなら教えていただきたいです🙏

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.assertIn("正しいユーザー名とパスワードを入力してください。", form.errors["__all__"][0])
「client.sessionにSESSION_KEYが含まれていない」こちらの要件もテストしてあげましょう！🔥
`assertNotIn`を使えばいい感じですね！👍

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.assertIn("正しいユーザー名とパスワードを入力してください。", form.errors["__all__"][0])
あとここの`[0]`も不要な気がします！！

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +
ここも「client.sessionにSESSION_KEYが含まれていない」こちらの要件もテストしてあげましょう！

2024-05-05 21:25 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.url = reverse("accounts:logout")
ここも`reverse(settings.LOGOUT_URL)`に変えちゃいましょう！

2024-05-07 05:30 UTC, renyagi commented on accounts/tests.py
> +        self.assertIn("正しいユーザー名とパスワードを入力してください。", form.errors["__all__"][0])
理由は分からないんですけど、要素番号を指定しないと文字列のみを抜き出せずタグが含まれてしまってエラーが出る感じです！

2024-05-08 16:46 UTC, renyagi commented on accounts/tests.py
> +        self.assertTrue(User.objects.filter(username=valid_data["username"]).exists())
サインアップのテストと同様にユーザーの有無を確認した方がいいのかと思いました！
ただ、ログインなので不要だとも思います！

2024-05-08 17:02 UTC, renyagi commented
分かりやすいレビュー感謝です🪇

2024-05-09 08:47 UTC, Ash1ey18 commented on accounts/tests.py
> +        self.assertIn("正しいユーザー名とパスワードを入力してください。", form.errors["__all__"][0])
`print(form.errors["__all__"])`でタグの中身確認してみてください！🧐
`<ul class="errorlist nonfield"><li>正しいユーザー名とパスワードを入力してください。どちらのフィールドも大文字と小文字は区別されます。</li></ul>`←こんな感じじゃないですかね？「どちらのフィールドも大文字と小文字は区別されます。」も含めてみたらどうでしょう？

2024-05-09 09:05 UTC, Ash1ey18 commented
あさひです！😌
修正お疲れ様です！
accounts/urls.py↓
`LoginView.as_view(template_name="accounts/login.html")`←`urls.py`内で完結させてるのいいですね！👍

templates/base.html↓ こんな感じでユーザがログインしているときだけ、ログアウトボタンを表示させるようにできます！👍
```
      {% if request.user.is_authenticated %}
        <form method="POST" action="/accounts/logout/"> {% csrf_token %}
          <button type="submit">ログアウト</button>
        </form>
      {% endif %}
```

2024-05-12 01:49 UTC, Ash1ey18 commented
お疲れ様です！
LGTM！！🔥🔥

2024-05-12 01:54 UTC, Ash1ey18 approved these changes

2024-05-13 14:40 UTC, gaato requested changes
一次レビューのときのコメントに補足しました！

2024-05-13 14:40 UTC, gaato commented on accounts/tests.py
> +        self.assertIn("正しいユーザー名とパスワードを入力してください。", form.errors["__all__"][0])
`form.errors["__all__"]` はエラーのリストなんですが、`print` すると（文字列にキャストすると）HTML 形式にフォーマットされます。
`form.errors["__all__"][0]` のままだと文字列の包含のチェックになるのですが、これだと正しくテストできない可能性があるので `str` と `list[str]` の比較にしてください（文字列同士は in ではなく = で比較する）。
@Ash1ey18 さんが書いた通り `正しいユーザー名とパスワードを入力してください。` だけだと不十分です。

2024-05-16 03:49 UTC, gaato requested changes

2024-05-16 03:49 UTC, gaato commented on accounts/tests.py
> +        )
それ自体は問題ないのですが他のテストでは `assertIn` で `str in list[str]` の比較をしているので，これも `assertIn` を使うか，他を全て `assertEqual` を `list[str] = list[str]` の比較にしたほうが統一性があって良いです．

2024-05-20 03:50 UTC, gaato approved these changes

2024-05-20 03:50 UTC, merged